<?php
/**
 * Copyright 2016 Shockwave-Design - J. & M. Kramer, all rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<script>
    require([
            "Magento_Ui/js/modal/confirm",
            "prototype"
        ], function(confirm){

//<!--
            mailControl = {
                reload: function (urlParams) {
                    if (!urlParams) {
                        urlParams = '';
                    }
                    var url = <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.url + '?ajax=true' + urlParams;
                    new Ajax.Updater(
                        <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.containerId,
                        url,
                        {
                            parameters: {form_key: FORM_KEY},
                            onComplete: <?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>.initGrid.bind(<?php /* @escapeNotVerified */ echo $block->getJsObjectName() ?>),
                        evalScripts:true
                        }
                    );
                },

                configureItem: function (itemId) {
                    productConfigure.setOnLoadIFrameCallback('mail', this.cbOnLoadIframe.bind(this));
                    productConfigure.showItemConfiguration('mail', itemId);
                    return false;
                },

                cbOnLoadIframe: function (response) {
                    if (!response.ok) {
                        return;
                    }
                    this.reload();
                }
            }
    });
</script>
